title: The Stress Factor
description: "Weekly solved problems for Mechanical Engineering Machine Design PE exam preparation."
baseurl: "" # Leave empty for root URL
url: "https://jonmurders.github.io/thestressfactor/" # Replace with your actual URL
theme: jekyll-theme-architect

# Optional: Customize the navigation menu
theme_config:
  navigation:
    - Home: /
    - About: /about
    - Contact: /contact

# Other optional settings
markdown: kramdown
highlighter: rouge
